# Generated by Django 4.0.4 on 2022-07-03 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_textwithword'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomWordForHomeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='words.words')),
            ],
        ),
    ]
