# Generated by Django 4.0.4 on 2022-07-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0003_randomwordforhomeview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=350)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.textwithword')),
            ],
        ),
        migrations.CreateModel(
            name='LikeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.textwithword')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsToComents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=64)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.commentstext')),
            ],
        ),
    ]
