# Generated by Django 4.0.4 on 2022-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_commentstext_liketext_commentstocoments'),
    ]

    operations = [
        migrations.AddField(
            model_name='textwithword',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
