# Generated by Django 4.0.4 on 2022-07-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_textwithword_no_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomwordforhomeview',
            name='create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
